### ISSUE TITLE
water buggy & end sky buggy

### ISSUE THREAD

**Issue by emolga45654** [DrDesten/DrDestens_McShader#8]
You've probably seen much of this water issue and you've addressed it as a mac/intel issue, but I have an AMD Radeon RX 6600M graphics card. I have the latest optifine (1.18.2) and the latest shaderpack installed.

Second, I haven't seen other people bring up this one- my end sky is completely blown out. When I try to adjust the sky color settings in "atmospheric" settings, the sky gets buggy.

![2022-03-24_23 46 18](https://user-images.githubusercontent.com/102341079/160050734-60e4bded-4555-4b7f-9e78-ad4f69077c18.png)
![2022-03-24_23 47 46](https://user-images.githubusercontent.com/102341079/160050739-4f8cb472-1479-43ce-a979-b3b12272c674.png)

I really love everything about this shaderpack and these two bugs are really the only things holding me back from using it. I hope you can figure them out!

**Comment by DrDesten** [comment]
The Water is a GPU related issue that seems to happen on some GPUs. I don't know what causes it, neither can I reproduce it, so I can't fix it. Sorry. That's what the option to disable water normals is for. In the future I might redo waves and it might simply disappear, but for now it's gonna stay.

As for the end sky, this is a "bug" in 1.18.2. Sky rendering is stopped during the boss fight, so unexpected stuff happens. I am looking into a way to fix this. Will probably be fixed in the next update. Other than that, just kill the ender dragon and it should stop.

**Comment by DrDesten** [comment]
Update is out!
